id: P000556
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:46:44.252364
source_metadata:
  id: bdr:W3CN6897
  title: བོད་ཀྱི་སྔ་རབས་ཁྲིམས་སྲོལ་ཡིག་ཆ་བདམས་བསྒྲིགས／
  author: ''
  volumes:
    85384e51ed5341c88822dd67435bf99c:
      image_group_id: I3CN6899
      title: Volume 1 of lha bla ma ye shes 'od kyi rnam thar/
      volume_number: 1
      total_pages: 326
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
